### ISSUE TITLE
Convert to just Plugin, not using the manifest

### ISSUE THREAD

**Issue by hybridherbst** [Seantron/MoverioUnityPlugin#1]
Hey,

it is possible to completely get rid of the dependency on a changed manifest, even when you need to access currentActivity. This is a showstopper right now, because it means that the functions (switch to 3D, change brightness) can't be accessed when you also use e.g. Metaio (which DOES need to overwrite the manifest already).

Could you change this to "not depending on a changed manifest", please?

**Comment by Seantron** [comment]
Nope, sorry, it's not that easy.. But I will setup a new version for Metaio over the weekend. Which will extend Metaio's functionality.
